version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
- package-ecosystem: gomod
  directory: "/api"
  schedule:
    interval: daily
- package-ecosystem: npm 
  directory: "/ui"
  schedule:
    interval: daily
- package-ecosystem: npm 
  directory: "/website"
  schedule:
    interval: daily