language: go

go:
  - 1.x

branches:
  only:
    - master

matrix:
  include:
    - env: GOTEST_PKGS="./api"
    - env: GOTEST_PKGS="./agent"
    - env: GOTEST_PKGS="./agent/consul"
    - env: GOTEST_PKGS="$(go list ./... | sed 's/github.com\/hashicorp\/consul/./' | egrep -v './agent|./agent/consul|./api')"

script:
  - GOTEST_FLAGS="-p 3 -parallel 1" make test

sudo: true
